### ISSUE TITLE
context view lists routes from other contexts

### ISSUE THREAD

**Issue by jcable** [sksamuel/camelwatch#7]
Hi,

  I deployed the CamelWatch 0.3 war in my tomcat6 container and set the properties as follows:

jmx.endpoint=service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi

The CamelWatch front page looks OK (see screenshot)
![screen shot 2016-03-22 at 09 25 24](https://cloud.githubusercontent.com/assets/152389/13947047/25fa9594-f010-11e5-8008-88a57a5c0991.png)

But when I click on a context it takes me to a list of all the routes in all the contexts, not all the routes in the selected context.

This is the traditional Camel Web Console view for one of my contexts:
![screen shot 2016-03-22 at 09 29 04](https://cloud.githubusercontent.com/assets/152389/13947162/bd7c795a-f010-11e5-9594-087433984935.png)

And this is part of the CamelWatch view:
![screen shot 2016-03-22 at 09 31 28](https://cloud.githubusercontent.com/assets/152389/13947190/eb9d7258-f010-11e5-9960-75739968ab46.png)

**Comment by sksamuel** [comment]
Unfortunately CamelWatch is no longer maintained.
